In [1]:
import pandas as pd
import numpy as np

In [2]:
op = pd.read_csv(r'results\operation_by_logreg.tsv', sep='\t')
op

     sensitivity    vocabulary
0       0.634707        energy
1       0.489471      electric
2       0.422937         solar
3       0.401854     operation
4       0.389663    commercial
..           ...           ...
495     0.227559          know
496     0.227559      buchanan
497     0.227559  gigacalories
498     0.227559         tally
499     0.227559  expansionist

[500 rows x 2 columns]

In [3]:
ca = pd.read_csv(r'results\cancelled_by_logreg.tsv', sep='\t')
ca

     sensitivity vocabulary
0       0.197078      solar
1       0.131873      state
2       0.130979       city
3       0.120024   projects
4       0.118999        key
..           ...        ...
495     0.090989     assess
496     0.090989    renewed
497     0.090989  secretary
498     0.090989        sum
499     0.090989      ducks

[500 rows x 2 columns]

In [4]:
de = pd.read_csv(r'results\delayed_by_logreg.tsv', sep='\t')
de

     sensitivity     vocabulary
0       0.041990        project
1       0.033366   transmission
2       0.032770           said
3       0.030538           line
4       0.029765           city
..           ...            ...
495     0.021724      secretary
496     0.021724  morphological
497     0.021724        worawut
498     0.021724       petredec
499     0.021724   punatsangchu

[500 rows x 2 columns]

In [5]:
ac = pd.read_csv(r'results\active_by_logreg.tsv', sep='\t')
ac

     sensitivity    vocabulary
0       0.721434  construction
1       0.627613       project
2       0.567686        county
3       0.547923   development
4       0.536108          site
..           ...           ...
495     0.480113        french
496     0.480113       albania
497     0.480113       evening
498     0.480113       burning
499     0.480113        indoor

[500 rows x 2 columns]

In [7]:
oplist = op['vocabulary'].tolist()
aclist = ac['vocabulary'].tolist()
calist = ca['vocabulary'].tolist()
delist = de['vocabulary'].tolist()

In [8]:
overlapped_op_ac = (set(oplist) & set(aclist))
overlapped_op_ca = (set(oplist) & set(calist))
overlapped_op_de = (set(oplist) & set(delist))
overlapped_ca_de = (set(calist) & set(delist))
overlapped_ca_ac = (set(calist) & set(aclist))
overlapped_de_ac = (set(delist) & set(aclist))


# overlapped_whole = (set(active_most_frequent_vocab) & set(operation_most_frequent_vocab) &
#                   set(cancelled_most_frequent_vocab) & set(delayed_most_frequent_vocab))
overlapped_op_ac

{'absaroka',
 'accrue',
 'accurate',
 'achievements',
 'acknowledged',
 'ad',
 'affordable',
 'aircraft',
 'ajk',
 'alchemy',
 'allegation',
 'analysers',
 'anju',
 'another',
 'assemblies',
 'attraction',
 'attribution',
 'auspices',
 'authorise',
 'axens',
 'azima',
 'bach',
 'baggage',
 'balboa',
 'batagram',
 'bdi',
 'beaches',
 'become',
 'berkeley',
 'berthed',
 'bich',
 'bolts',
 'bridges',
 'bring',
 'buchanan',
 'button',
 'caas',
 'cables',
 'caf',
 'calculated',
 'calculation',
 'cankurtaran',
 'cant',
 'capacity',
 'cape',
 'caracas',
 'cargolux',
 'ceará',
 'cent',
 'chakaria',
 'charges',
 'chen',
 'chiefly',
 'choose',
 'chukiatan',
 'claxton',
 'climb',
 'coffee',
 'commonweath',
 'compassion',
 'competent',
 'competes',
 'configuration',
 'conflicting',
 'conservator',
 'contentious',
 'conventional',
 'cooperative',
 'coordinator',
 'cosmetic',
 'counterproductive',
 'cranes',
 'critics',
 'crouse',
 'cryogenic',
 'csr',
 'dahm',
 'daovong',
 'daunting',
 'deadly',
 'debilitating',
 'december',
 'decimate',
 'dells',
 'denies',
 'deny',
 'derail',
 'describes',
 'deter',
 'devanadera',
 'devastated',
 'dismantled',
 'diverse',
 'dmtcl',
 'dunya',
 'eaeu',
 'ebitda',
 'ebtke',
 'ecuador',
 'edit',
 'edozien',
 'eetc',
 'egress',
 'eia',
 'electrochemical',
 'employers',
 'endorsement',
 'endorsing',
 'eng',
 'engelbert',
 'enoc',
 'enthusiasm',
 'envisaged',
 'epe',
 'erdoğan',
 'essel',
 'et',
 'exhibiting',
 'expensed',
 'extnesion',
 'falling',
 'farmland',
 'farruggio',
 'feather',
 'filling',
 'films',
 'financed',
 'fire',
 'flatirons',
 'foreurs',
 'garber',
 'gauge',
 'general',
 'geronimo',
 'gezhouba',
 'giorgio',
 'goes',
 'gordon',
 'grants',
 'greco',
 'greenpeace',
 'guarders',
 'guests',
 'guidelines',
 'gulam',
 'habib',
 'habitat',
 'haskoning',
 'hastings',
 'hat',
 'hatirjheel',
 'helpful',
 'hired',
 'holdup',
 'hollow',
 'hydraulics',
 'hydrocarbon',
 'iceberg',
 'iddah',
 'ignoring',
 'impending',
 'implemented',
 'index',
 'indices',
 'indonesian',
 'industrialist',
 'information',
 'injustices',
 'interchangeable',
 'interestin',
 'interesting',
 'intermittent',
 'iogp',
 'irish',
 'jaganmohan',
 'japanese',
 'jobs',
 'jostle',
 'juárez',
 'ka',
 'kajima',
 'kalapara',
 'kano',
 'karamehmetoğlu',
 'khurshedul',
 'kilometre',
 'kmp',
 'knit',
 'know',
 'knows',
 'kpcl',
 'ktdp',
 'kurrum',
 'largest',
 'laukhali',
 'legal',
 'lend',
 'leone',
 'lianyungang',
 'lifting',
 'lighterage',
 'likes',
 'lmrc',
 'locating',
 'logistics',
 'loke',
 'longest',
 'malolos',
 'management',
 'mangrove',
 'manshera',
 'market',
 'marquee',
 'matakong',
 'maturity',
 'mayawati',
 'meals',
 'medog',
 'members',
 'memoranda',
 'mexico',
 'mild',
 'million',
 'mizohu',
 'mizuho',
 'monuments',
 'mostafa',
 'mps',
 'mutually',
 'myingyan',
 'namanga',
 'nea',
 'nee',
 'negatively',
 'newest',
 'nonprofit',
 'officials',
 'offset',
 'omanis',
 'oppose',
 'ores',
 'organizations',
 'outlines',
 'outweighed',
 'overview',
 'pampa',
 'parbatipur',
 'patil',
 'peak',
 'penh',
 'perhaps',
 'permanent',
 'pertaining',
 'phasing',
 'phillips',
 'pickering',
 'po',
 'pollster',
 'possibility',
 'power',
 'principal',
 'pro',
 'procuring',
 'prohibitively',
 'proportion',
 'proud',
 'provided',
 'pumping',
 'pupils',
 'rahmon',
 'rank',
 'rate',
 'reasonably',
 'rebuilding',
 'reconnaissance',
 'reconsider',
 'recoup',
 'reduce',
 'reimbursement',
 'relief',
 'renaissance',
 'repatriation',
 'report',
 'resettling',
 'responding',
 'restrict',
 'retailer',
 'ripening',
 'ritual',
 'robjohns',
 'role',
 'rovno',
 'runways',
 'sadly',
 'salalah',
 'saleem',
 'samsung',
 'sanctioned',
 'sangu',
 'sanmen',
 'santa',
 'section',
 'semco',
 'settings',
 'shell',
 'shipments',
 'shot',
 'show',
 'sicomines',
 'siddiqui',
 'significantly',
 'six',
 'sized',
 'sketch',
 'skyscrapers',
 'slhp',
 'slide',
 'smb',
 'smelter',
 'solution',
 'sometime',
 'special',
 'spectrum',
 'spending',
 'srivastava',
 'stabilise',
 'steadfast',
 'stealing',
 'stgs',
 'stranded',
 'structured',
 'structures',
 'supplier',
 'supposedly',
 'taiwan',
 'takashimaya',
 'tallest',
 'tara',
 'tariff',
 'taxes',
 'tc',
 'teach',
 'technipfmc',
 'temperature',
 'tempting',
 'tennet',
 'termination',
 'tested',
 'tetas',
 'thankful',
 'thermax',
 'thi',
 'thimphu',
 'though',
 'thunderstorm',
 'tickets',
 'tokheim',
 'torn',
 'tougher',
 'towage',
 'tpy',
 'transmilenio',
 'tremblay',
 'trenches',
 'tserenpil',
 'tsu',
 'tuesday',
 'turkana',
 'turning',
 'unconfirmed',
 'unless',
 'unsurpassed',
 'upgrades',
 'urdu',
 'valdi',
 'vicente',
 'violates',
 'voiceless',
 'volumes',
 'vst',
 'walter',
 'wanted',
 'wheelabrator',
 'whether',
 'williams',
 'windpark',
 'wins',
 'wishes',
 'witnessed',
 'woldehanna',
 'woodfibre',
 'worksite',
 'wrapped',
 'wynn',
 'yet',
 'youths',
 'zambezi',
 'ömer',
 'ل'}

In [9]:
def exclude_overlapped_ones_simple(target_vocab:list, target:pd.core.series.Series, status1:set, status2:set, status3:set):
    excluded_indexer = list(set(target_vocab) - status1 - status2 - status3)
    excluded = target.loc[excluded_indexer]
    return excluded

In [14]:
# ac = ac.set_index('vocabulary')
ac_series = ac['sensitivity']
type(ac_series)

pandas.core.series.Series

In [15]:
ac_series

vocabulary
construction    0.721434
project         0.627613
county          0.567686
development     0.547923
site            0.536108
                  ...
french          0.480113
albania         0.480113
evening         0.480113
burning         0.480113
indoor          0.480113
Name: sensitivity, Length: 500, dtype: float64

In [16]:
op = op.set_index('vocabulary')
op_series = op['sensitivity']

ca = ca.set_index('vocabulary')
ca_series = ca['sensitivity']

de = de.set_index('vocabulary')
de_series = de['sensitivity']

In [17]:
op_result = exclude_overlapped_ones_simple(oplist, op_series, overlapped_op_ac, overlapped_op_ca, overlapped_op_de)

In [18]:
ca_result = exclude_overlapped_ones_simple(calist, ca_series, overlapped_ca_ac, overlapped_op_ca, overlapped_ca_de)

In [19]:
de_result = exclude_overlapped_ones_simple(delist, de_series, overlapped_de_ac, overlapped_ca_de, overlapped_op_de)

In [20]:
ac_result = exclude_overlapped_ones_simple(aclist, ac_series, overlapped_op_ac, overlapped_ca_ac, overlapped_de_ac)

In [27]:
len(op_result)

67

In [24]:
len(ca_result)

26

In [25]:
len(ac_result)

20

In [26]:
len(de_result)

11